
liste_enigmes = ["Si cela cache, ce n'est que pour mieux révéler.\nCela bloque autant que cela permet de passer.\nLa réponse est dans la question.\nQue suis-je ?",
     "Je suis le commencement de l’effroi,\nLa fin de la durée et de l’espace,\nLe commencement de toutes extrémités,\nEt la fin de chaque contrée.\nQui suis-je ?",
     "Celui qui le fabrique le vend,\nCelui qui l'achète ne s'en sert pas,\nCelui qui s'en sert ne le sais pas.\nQu'est-ce ?",
     "Je serai hier, j'étais demain.",
      "Je suis si fragile que lorsque l'on prononce mon nom, je meurs.",
      "Je suis tout au bout de ta main,\nJe commence la nuit et je finis demain.",
      "Je me vide en me remplissant,\nEt je me remplis en me vidant,\nQue suis-je?",
      "Les feignant me vénèrent, mais je suis leur pire énemie.\nLes travailleurs me craignent mais je pourrais les soulager.\nQue suis-je ?",
      "Plus j'ai de gardien, moins je suis en sécurité\nMoins j'ai de gardien, plus je suis en sécurité.\nQue suis-je ?",
      "Une boite sans charnière, sans clé, sans couvercle.\nPourtant à l'intérieur est caché un trésor doré.",
      "Lors d'une guerre, un chevalier fut transpercé, il en mourrut,\nun deuxiéme guerrier fut décapité et les deux écuiers eurent la tête tranchée.\nCombien y a-t-il eu de morts ?",
      "Lumières qui fuient la lumière.",
      "Vivant sans souffle,\nFroid comme la mort,\nJamais assoiffé, toujours buvant,\nEn cotte de mailles, jamais cliquetant.",
      "Sans pieds, Sans mains, Sans ailes,\nje monte au ciel.",
      "Tellement magique qu'il vient à vous tous les soirs,\nIl vous emmène partout sans vous déplacer.\nPour le voir, vous devez d'abord fermer les yeux."]
liste_reponses = [("une enigme", "une énigme"),
       ("le e", " la lettre e", " le E"),
       "un cercueil",
       "aujourd'hui",
        "le silence",
        ("le n", "la lettre n", "le N"),
        "un sablier",
        "l'ennui",
        "un secret",
        "un oeuf",
        ("2", "deux"),
        ("les etoiles", "les étoiles"),
        "un poisson",
        ('une âme', 'une ame', 'la fumée', 'de la fumée'),
        ('le rêve', 'un rêve')]
liste_indices = ["Cette énigme est une énigme de niveau 3, par conséquent il n'y a pas d'indice disponible",
           "la réponse comporte 4 caractère, déterminant et espace compris",
           "c'est matériel",
           "c'est un moment",
           "c'est immatériel",
           "la réponse comporte 4 caractère, déterminant et espace compris",
           "Cette énigme est une énigme de niveau 3, par conséquent il n'y a pas d'indice disponible",
           "long de 5 caractère (déterminant et espace(s) eventuel(s) non compris), ça commence par un 'e'",
           "c'est immatériel",
           "ne pas prendre les mots au pied de la lettre",
           "faire attention aux sens de 'eurent'",
           "Cette énigme est une énigme de niveau 3, par conséquent il n'y a pas d'indice disponible",
           "le poid du son",
           "Cette énigme est une énigme de niveau 3, par conséquent il n'y a pas d'indice",
           ""]
           
enigmes = {
    'e1' : liste_enigmes[0],
    'e2' : liste_enigmes[1],
    'e3' : liste_enigmes[2],
    'e4' : liste_enigmes[3],
    'e5' : liste_enigmes[4],
    'e6' : liste_enigmes[5],
    'e7' : liste_enigmes[6],
    'e8' : liste_enigmes[7],
    'e9' : liste_enigmes[8],
    'e10' : liste_enigmes[9],
    'e11' : liste_enigmes[10],
    'e12' : liste_enigmes[11],
    'e13' : liste_enigmes[12]
}

reponses = {
    'rep e1' : liste_reponses[0],
    'rep e2' : liste_reponses[1],
    'rep e3' : liste_reponses[2],
    'rep e4' : liste_reponses[3],
    'rep e5' : liste_reponses[4],
    'rep e6' : liste_reponses[5],
    'rep e7' : liste_reponses[6],
    'rep e8' : liste_reponses[7],
    'rep e9' : liste_reponses[8],
    'rep e10' : liste_reponses[9],
    'rep e11' : liste_reponses[10],
    'rep e12' : liste_reponses[11],
    'rep e13' : liste_reponses[12]
}

indices = {
    'i 1' : liste_indices[0],
    'i 2' : liste_indices[1],
    'i 3' : liste_indices[2],
    'i 4' : liste_indices[3],
    'i 5' : liste_indices[4],
    'i 6' : liste_indices[5],
    'i 7' : liste_indices[6],
    'i 8' : liste_indices[7],
    'i 9' : liste_indices[8],
    'i 10' : liste_indices[9],
    'i 11' : liste_indices[10],
    'i 12' : liste_indices[11],
    'i 13' : liste_indices[12]
}